# -*- coding: utf-8 -*-
"""triangle_calculator

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Eq8gadEZIS7xuKNwCAX9563cuh-wipti
"""

import math

print("Welcome to the Triangle Calculator.")
print(" ")

def calculate_area():
    base = float(input("Enter the value of the base of the triangle: "))
    height = float(input("Enter the value of the height of the triangle: "))
    area = (base * height) / 2
    print("The area of the triangle is: " + str(round(area, 2)))

def calculate_angles_and_type():
    a = float(input("Enter the value of side a: "))
    b = float(input("Enter the value of side b: "))
    c = float(input("Enter the value of side c: "))

    # Check the type of the triangle
    if a == b == c:
        print("The triangle is equilateral.")
    elif a == b or b == c or a == c:
        print("The triangle is isosceles.")
    else:
        print("The triangle is scalene.")

    # Law of Cosines to calculate the angles
    angle_A = math.degrees(math.acos((b**2 + c**2 - a**2) / (2 * b * c)))
    angle_B = math.degrees(math.acos((a**2 + c**2 - b**2) / (2 * a * c)))
    angle_C = math.degrees(math.acos((a**2 + b**2 - c**2) / (2 * a * b)))

    print("The angles of the triangle are:")
    print("Angle A: " + str(round(angle_A, 2)) + " degrees")
    print("Angle B: " + str(round(angle_B, 2)) + " degrees")
    print("Angle C: " + str(round(angle_C, 2)) + " degrees")

def show_menu():
    print("\nMenu:")
    print("1. Calculate the area of the triangle.")
    print("2. Calculate the angles and type of the triangle.")
    print("3. Exit.")

    option = 0
    while option != 3:
        option = int(input("Choose an option (1, 2, or 3): "))

        if option == 1:
            print("You chose Option 1! Calculate the area of the triangle.")
            calculate_area()
        elif option == 2:
            print("You chose Option 2! Calculate the angles and type of the triangle.")
            calculate_angles_and_type()
        elif option == 3:
            print("Exiting the program...")
        else:
            print("Invalid option! Please try again.")

# Calling the show_menu function to display the menu
show_menu()